name: bf-mall-ci
# 手动触发
on: workflow_dispatch

#流程
jobs:
  my_first:
    name: My first job
    runs-on: ubuntu-18.04
    steps:
      - run: echo helo world by bf-mall
  my_second:
    name: MY second job
    runs-on: ubuntu-18.04
    # 依赖my_first先完成
    needs: my_first
    steps:
      - run: echo helo world by bf-mall 2
