# 名称，随便起
name: bf-mall-ci
# 手动触发
on: workflow_dispatch

# 流程
jobs:
  # 流程名称
  my_first:
    name: My first job
    # 运行环境
    runs-on: ubuntu-18.04
    # 步骤，可以有很多
    steps:
      # 通过远程触发jenkins的构建，token是在jenkins中配置的，必须配置登录的用户，否则会报错
      - run: curl ${{ secrets.JENKINS_URL }} --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_PWD }}
